kind: Service
apiVersion: v1
metadata:
  name: xpartla-pharmacy-webapi
spec:
  selector:
    pod: xpartla-pharmacy-webapi-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: webapi-port
