/*
 * Pharmacy Product Api
 *
 * Pharmacy product inventory for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpartla@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_product

import (
	"github.com/gin-gonic/gin"
)

type PharmaciesAPI interface {


    // CreatePharmacy Post /api/pharmacy
    // Saves new pharmacy definition 
     CreatePharmacy(c *gin.Context)

    // DeletePharmacy Delete /api/pharmacy/:pharmacyId
    // Deletes specific pharmacy 
     DeletePharmacy(c *gin.Context)

}