/*
 * Pharmacy Product Api
 *
 * Pharmacy product inventory for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpartla@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_product

import (
	"github.com/gin-gonic/gin"
)

type DepartmentOrdersAPI interface {

	// CreateDepartmentOrder Post /api/orders/:pharmacyId/items
	// Saves new department order into the pharmacy
	CreateDepartmentOrder(c *gin.Context)

	// DeleteDepartmentOrder Delete /api/orders/:pharmacyId/items/:orderId
	// Cancels or archives department order
	DeleteDepartmentOrder(c *gin.Context)

	// GetDepartmentOrder Get /api/orders/:pharmacyId/items/:orderId
	// Provides details about a single department order
	GetDepartmentOrder(c *gin.Context)

	// GetDepartmentOrders Get /api/orders/:pharmacyId/items
	// Provides the department order list
	GetDepartmentOrders(c *gin.Context)

	// UpdateDepartmentOrder Put /api/orders/:pharmacyId/items/:orderId
	// Updates specific department order
	UpdateDepartmentOrder(c *gin.Context)
}
