/*
 * Pharmacy Product Api
 *
 * Pharmacy product inventory for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpartla@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_product

import (
	"github.com/gin-gonic/gin"
)

type PharmacyProductsAPI interface {


    // CreateProduct Post /api/products/:pharmacyId/items
    // Saves new product into the pharmacy 
     CreateProduct(c *gin.Context)

    // DeleteProduct Delete /api/products/:pharmacyId/items/:productId
    // Soft-deletes a product (sets active=false) 
     DeleteProduct(c *gin.Context)

    // GetProduct Get /api/products/:pharmacyId/items/:productId
    // Provides details about a single product 
     GetProduct(c *gin.Context)

    // GetProducts Get /api/products/:pharmacyId/items
    // Provides the pharmacy product list 
     GetProducts(c *gin.Context)

    // UpdateProduct Put /api/products/:pharmacyId/items/:productId
    // Updates specific product 
     UpdateProduct(c *gin.Context)

}