/*
 * Pharmacy Product Api
 *
 * Pharmacy product inventory for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpartla@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_product

import (
	"github.com/gin-gonic/gin"
)

type PharmacyCategoriesAPI interface {


    // GetCategories Get /api/products/:pharmacyId/categories
    // Provides the list of categories defined for the pharmacy 
     GetCategories(c *gin.Context)

}