/*
 * Pharmacy Product Api
 *
 * Pharmacy product inventory for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpartla@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_product

type Product struct {

	// Unique id of the product within the pharmacy
	Id string `json:"id"`

	Name string `json:"name"`

	Category Category `json:"category,omitempty"`

	Stock int32 `json:"stock"`

	// Soft-delete flag; the listing endpoint hides inactive products.
	Active bool `json:"active"`
}
