/*
 * Pharmacy Product Api
 *
 * Pharmacy product inventory for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpartla@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_product

type Pharmacy struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Address string `json:"address,omitempty"`

	Products []Product `json:"products,omitempty"`

	PredefinedCategories []Category `json:"predefinedCategories,omitempty"`
}
