/*
 * Pharmacy Product Api
 *
 * Pharmacy product inventory for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpartla@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_product

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the PharmaciesAPI part of the API
	PharmaciesAPI PharmaciesAPI
	// Routes for the PharmacyCategoriesAPI part of the API
	PharmacyCategoriesAPI PharmacyCategoriesAPI
	// Routes for the PharmacyProductsAPI part of the API
	PharmacyProductsAPI PharmacyProductsAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"CreatePharmacy",
			http.MethodPost,
			"/api/pharmacy",
			handleFunctions.PharmaciesAPI.CreatePharmacy,
		},
		{
			"DeletePharmacy",
			http.MethodDelete,
			"/api/pharmacy/:pharmacyId",
			handleFunctions.PharmaciesAPI.DeletePharmacy,
		},
		{
			"GetCategories",
			http.MethodGet,
			"/api/products/:pharmacyId/categories",
			handleFunctions.PharmacyCategoriesAPI.GetCategories,
		},
		{
			"CreateProduct",
			http.MethodPost,
			"/api/products/:pharmacyId/items",
			handleFunctions.PharmacyProductsAPI.CreateProduct,
		},
		{
			"DeleteProduct",
			http.MethodDelete,
			"/api/products/:pharmacyId/items/:productId",
			handleFunctions.PharmacyProductsAPI.DeleteProduct,
		},
		{
			"GetProduct",
			http.MethodGet,
			"/api/products/:pharmacyId/items/:productId",
			handleFunctions.PharmacyProductsAPI.GetProduct,
		},
		{
			"GetProducts",
			http.MethodGet,
			"/api/products/:pharmacyId/items",
			handleFunctions.PharmacyProductsAPI.GetProducts,
		},
		{
			"UpdateProduct",
			http.MethodPut,
			"/api/products/:pharmacyId/items/:productId",
			handleFunctions.PharmacyProductsAPI.UpdateProduct,
		},
	}
}
